# Restart positional tracking to a new pose in base_link frame

# Translation XYZ [meters]
float32[3] pos
# Orientation RPY [radians]
float32[3] orient
---
bool success   # indicate successful run of service
string message # informational, e.g. for error messages
