# config/zedxm_yaml
# Parameters for Stereolabs ZED X Mini camera
---
/**:
    ros__parameters:
        general:
          camera_model: 'zedxm'
          camera_name: 'zedxm' # usually overwritten by launch file
          grab_resolution: 'HD1200' # The native camera grab resolution. 'HD1200', 'HD1080', 'SVGA', 'AUTO'
          grab_frame_rate: 30 # ZED SDK internal grabbing rate (HD1200/HD1080: 60, 30, 15 - SVGA: 120, 60, 30, 15)

        video:
          exposure_time: 16666 # Defines the real exposure time in microseconds. Recommended to control manual exposure (instead of `video.exposure` setting)
          auto_exposure_time_range_min: 28 # Defines the minimum range of exposure auto control in micro seconds
          auto_exposure_time_range_max: 16666 # Defines the maximum range of exposure auto control in micro seconds
          exposure_compensation: 50 # Defines the Exposure-target compensation made after auto exposure. Reduces the overall illumination target by factor of F-stops. Values range is [0 - 100]. Default value is 50, i.e. no compensation applied
          analog_gain: 8000 # Defines the real analog gain (sensor) in mDB. Range [1000-16000]. Recommended to control manual sensor gain (instead of `video.gain` setting)
          auto_analog_gain_range_min: 1000 # Defines the minimum range of sensor gain in automatic control
          auto_analog_gain_range_max: 16000 # Defines the maximum range of sensor gain in automatic control
          digital_gain: 128 # Defines the real digital gain (ISP) as a factor. Range [1-256]. Recommended to control manual ISP gain (instead of `video.gain` setting)
          auto_digital_gain_range_min: 1 # Defines the minimum range of digital ISP gain in automatic control
          auto_digital_gain_range_max: 256 # Defines the maximum range of digital ISP gain in automatic control
          denoising: 50 # Defines the level of denoising applied on both left and right images. Range [0-100]

        depth:
          min_depth: 0.3 # Min: 0.3, Max: 3.0
          max_depth: 10.0 # Max: 20.0

