# Set the Region of Interest for ZED SDK computing

# Region of interest polygon as an array of normalized vertices. e.g. "[[0.5,0.25],[0.75,0.5],[0.5,0.75],[0.25,0.5]]"
# You can use
string roi
---
bool success   # indicate successful run of service
string message # informational, e.g. for error messages
