# Start SVO Recording

# Bitrate - 0 or [1000,60000]
uint32 bitrate

# Compression Mode - [0,2]
uint8 compression_mode

# Target Framerate
# Allowed framerates are 0,15,30, 60 or 100. 
# Any other values will be discarded and camera FPS will be taken.
uint32 target_framerate

# Input Transcode
bool input_transcode

# Filename
string svo_filename 
---
bool success   # indicate successful run of service
string message # informational, e.g. for error messages
